### ISSUE TITLE
怎么设置saga.InitSagaAgent的coordinatorAddress？

### ISSUE THREAD

**Issue by leenux** [jeremyxu2010/matrix-saga-go#1]
demo没运行起来

**Comment by jeremyxu2010** [comment]
> demo没运行起来

@leenux 参考[这里](https://github.com/apache/servicecomb-pack/blob/master/docs/user_guide_zh.md#%E5%A6%82%E4%BD%95%E8%BF%90%E8%A1%8C)，先把alpha-server运行起来,coordinatorAddress即为alpha-server的gRPC地址，一般为${alpha_server_ip}:8080

**Comment by leenux** [comment]
@jeremyxu2010 好的 非常感谢
